### ISSUE TITLE
Unable to skip

### ISSUE THREAD

**Issue by BenStigsen** [Adivise/DisSpaceX#2]
The bot and effects work great, but it seems that I'm unable to skip the song currently playing. Because "no songs are in queue" even though a song is playing.

**Comment by XeonE52680v3** [comment]
I think the issue happen when you are playing only 1 song in the queue. If yes, all you need to do is add more song in to your current queue when you using your bot. If no, I think this is the issue from  play.js not support queue more than 1 song, with that issue, you just wait for the next update or using NanoSpace instead.

**Comment by CASPERg267** [comment]
@BenStigsen after last pull request could you check if the problem persists?
