### ISSUE TITLE
Hey! READ THIS!

### ISSUE THREAD

**Issue by Adivise** [Adivise/DisSpaceX#7]
Hm yeah i have a plan to update `DisSpaceX` to `SlashCommands!`
But use original concept (Performance First!)

## Progress [Rest]

- [x] Move `PrefixCommands!!` to `SlashCommands!!`
- [x] More Handlers!
- [x] More Configs!  (25%)
- [x] More Events!
- [x] More Commands? (70%)
- [x] Database (Json)
- [ ] ~~Multi Languages (In Progress!)~~
- [x] Seen community

**Comment by adh319** [comment]
so the prefix version will be gone later?
